import Mathlib

-- BEGIN INLINED FILE: Mathlib/Support/stable_unstable_manifolds_da940581de/ComplexEigen.lean

open scoped TensorProduct
open Polynomial

namespace StableSupport
variable {W : Type*} [AddCommGroup W] [Module ℝ W] [FiniteDimensional ℝ W]

/-- A nonzero finite-dimensional real space acquires an eigenvalue after
extending the scalars to the complexes. Kept in root form to avoid choices. -/
theorem exists_complex_root (hne : Nontrivial W) (D : W →ₗ[ℝ] W) :
    ∃ μ : ℂ, (D.charpoly.map (algebraMap ℝ ℂ)).IsRoot μ := by
  classical
  letI : Nontrivial W := hne
  let U := TensorProduct ℝ ℂ W
  have hd : Module.finrank ℂ U = Module.finrank ℝ W := by
    simpa [U] using (Module.finrank_baseChange (R:=ℂ) (S:=ℝ) (M':=W))
  have hp : 0 < Module.finrank ℂ U := by
    rw [hd]
    exact Module.finrank_pos
  letI : Nontrivial U := Module.finrank_pos_iff.mp hp
  let D' : Module.End ℂ U := LinearMap.baseChange ℂ D
  obtain ⟨μ, hμ⟩ := Module.End.exists_eigenvalue D'
  refine ⟨μ, ?_⟩
  rw [← LinearMap.charpoly_baseChange]
  exact (Module.End.hasEigenvalue_iff_isRoot_charpoly D' μ).1 hμ
end StableSupport

namespace StableSupport
open scoped TensorProduct
open Polynomial
variable {V : Type*} [AddCommGroup V] [Module ℝ V] [FiniteDimensional ℝ V]
variable (A : V →ₗ[ℝ] V) (P : Submodule ℝ V) (D : P →ₗ[ℝ] P)

/-- Roots of the complexified restriction are roots of the complexified ambient
endomorphism. The intertwining hypothesis is often easier than matrices. -/
theorem ambient_root_of_restriction
    (hint : P.subtype ∘ₗ D = A ∘ₗ P.subtype)
    {μ : ℂ} (hμ : (D.charpoly.map (algebraMap ℝ ℂ)).IsRoot μ) :
    (A.charpoly.map (algebraMap ℝ ℂ)).IsRoot μ := by
  classical
  -- a left inverse to the inclusion remains a left inverse after base change
  obtain ⟨p, hp⟩ := P.subtype.exists_leftInverse_of_injective P.ker_subtype
  have hp' : (LinearMap.baseChange ℂ p) ∘ₗ
        (LinearMap.baseChange ℂ P.subtype) = LinearMap.id := by
    rw [← LinearMap.baseChange_comp]
    rw [hp]
    exact LinearMap.baseChange_id
  have hj : Function.Injective (LinearMap.baseChange ℂ P.subtype) := by
    intro x y hxy
    have := congrArg (fun t => (LinearMap.baseChange ℂ p) t) hxy
    calc
      x = (LinearMap.baseChange ℂ p) ((LinearMap.baseChange ℂ P.subtype) x) := by
        rw [← LinearMap.comp_apply, hp']
        rfl
      _ = (LinearMap.baseChange ℂ p) ((LinearMap.baseChange ℂ P.subtype) y) := this
      _ = y := by rw [← LinearMap.comp_apply, hp']; rfl
  let D' : Module.End ℂ (TensorProduct ℝ ℂ P) := LinearMap.baseChange ℂ D
  let A' : Module.End ℂ (TensorProduct ℝ ℂ V) := LinearMap.baseChange ℂ A
  let j : TensorProduct ℝ ℂ P →ₗ[ℂ] TensorProduct ℝ ℂ V :=
    LinearMap.baseChange ℂ P.subtype
  have hinter : j ∘ₗ D' = A' ∘ₗ j := by
    dsimp [j, D', A']
    rw [← LinearMap.baseChange_comp, ← LinearMap.baseChange_comp, hint]
  have hev : D'.HasEigenvalue μ := by
    apply (Module.End.hasEigenvalue_iff_isRoot_charpoly D' μ).2
    simpa [D', LinearMap.charpoly_baseChange] using hμ
  obtain ⟨w, hw⟩ := hev.exists_hasEigenvector
  have hw0 : w ≠ 0 := hw.2
  have hjw : j w ≠ 0 := by
    intro hz; exact hw0 (hj (by simpa using hz))
  have heq : A' (j w) = μ • (j w) := by
    have he := hw.apply_eq_smul
    have he' := LinearMap.congr_fun hinter w
    -- intertwine, then the eigen equation
    simpa [LinearMap.comp_apply, he, map_smul] using he'.symm
  have heig : A'.HasEigenvalue μ :=
    Module.End.hasEigenvalue_of_hasEigenvector
      ⟨(Module.End.mem_eigenspace_iff).2 heq, hjw⟩
  have := (Module.End.hasEigenvalue_iff_isRoot_charpoly A' μ).1 heig
  simpa [A', LinearMap.charpoly_baseChange] using this
end StableSupport

-- END INLINED FILE: Mathlib/Support/stable_unstable_manifolds_da940581de/ComplexEigen.lean

-- BEGIN INLINED FILE: Mathlib/Support/stable_unstable_manifolds_da940581de/OrbitSpan.lean

namespace StableSupport

variable {V : Type*} [AddCommGroup V] [Module ℝ V]

/-- The subspace generated by all the translates of a two sided orbit. -/
def orbitSpan (u : ℤ → V) : Submodule ℝ V :=
  Submodule.span ℝ (Set.range u)

lemma orbit_mem_orbitSpan (u : ℤ → V) (i : ℤ) : u i ∈ orbitSpan u :=
  Submodule.subset_span (Set.mem_range_self i)

lemma orbitSpan_ne_bot (u : ℤ → V) (i : ℤ) (hi : u i ≠ 0) : orbitSpan u ≠ ⊥ := by
  intro h
  have hz : u i ∈ (⊥ : Submodule ℝ V) := h ▸ orbit_mem_orbitSpan u i
  simpa using hi (by simpa using hz)

lemma map_orbitSpan (A : V →ₗ[ℝ] V) (u : ℤ → V)
    (hu : ∀ i : ℤ, u (i+1) = A (u i)) :
    Submodule.map A (orbitSpan u) = orbitSpan u := by
  apply le_antisymm
  · -- it is invariant
    refine (Submodule.map_le_iff_le_comap).2 ?_
    -- It suffices to check the generators of the span.
    refine (Submodule.span_le).2 ?_
    intro x hx
    rcases hx with ⟨i, rfl⟩
    change A (u i) ∈ orbitSpan u
    rw [← hu i]
    exact orbit_mem_orbitSpan u (i+1)
  · -- every generator is itself an image, using the predecessor
    refine (Submodule.span_le).2 ?_
    intro x hx
    rcases hx with ⟨i, rfl⟩
    refine ⟨u (i-1), orbit_mem_orbitSpan u (i-1), ?_⟩
    have hh := hu (i-1)
    -- `(i-1)+1=i`
    simpa [sub_eq_add_neg, add_assoc] using hh.symm

/-- Restriction of an endomorphism to the span of an orbit. -/
noncomputable def orbitRestriction (A : V →ₗ[ℝ] V) (u : ℤ → V)
    (hu : ∀ i : ℤ, u (i+1) = A (u i)) :
    orbitSpan u →ₗ[ℝ] orbitSpan u :=
  A.restrict (p := orbitSpan u) (q := orbitSpan u) (by
    intro x hx
    have hm : Submodule.map A (orbitSpan u) = orbitSpan u :=
      map_orbitSpan A u hu
    have : A x ∈ Submodule.map A (orbitSpan u) :=
      ⟨x, hx, rfl⟩
    simpa [hm] using this)

lemma orbitRestriction_apply_coe (A : V →ₗ[ℝ] V) (u : ℤ → V)
    (hu : ∀ i : ℤ, u (i+1) = A (u i)) (x : orbitSpan u) :
    ((orbitRestriction A u hu x : orbitSpan u) : V) = A (x:V) := rfl

lemma orbitRestriction_surjective (A : V →ₗ[ℝ] V) (u : ℤ → V)
    (hu : ∀ i : ℤ, u (i+1) = A (u i)) :
    Function.Surjective (orbitRestriction A u hu) := by
  intro y
  have hm : Submodule.map A (orbitSpan u) = orbitSpan u :=
    map_orbitSpan A u hu
  have hy : (y:V) ∈ Submodule.map A (orbitSpan u) := by
    have : (y:V) ∈ orbitSpan u := y.property
    rwa [hm]
  rcases hy with ⟨x, hx, hxy⟩
  refine ⟨⟨x, hx⟩, ?_⟩
  apply Subtype.ext
  exact hxy

end StableSupport

-- END INLINED FILE: Mathlib/Support/stable_unstable_manifolds_da940581de/OrbitSpan.lean

-- BEGIN INLINED FILE: Mathlib/Support/stable_unstable_manifolds_da940581de/Pseudo.lean

open Filter
open scoped Topology

/-! Compactness form of the elementary ``no almost orbit'' lemma.

This file is just some general (finite dimensional) real analysis; no reference to
the dynamical statement is made.  It is useful to formulate the conclusion with
`≤`: this avoids choices of operator norms later.
-/
namespace StableSupport

variable {X : Type*} [NormedAddCommGroup X] [NormedSpace ℝ X]

/-- There is a definite error in any normalized bounded two sided pseudo orbit. -/
def NoSmallBoundedPseudoOrbit (T : X →L[ℝ] X) : Prop :=
  ∃ e : ℝ, 0 < e ∧
    ∀ u : ℤ → X, (∀ i, ‖u i‖ ≤ 1) → ‖u 0‖ = 1 →
      ¬ (∀ i, ‖u (i+1) - T (u i)‖ ≤ e)

variable [FiniteDimensional ℝ X]

/-- A compactness observation: if there is no (normalized bounded) exact
orbit, there is already no such orbit with arbitrarily small uniform errors.
This is at times a convenient substitute for choosing an adapted norm. -/
theorem noSmall_of_no_exact (T : X →L[ℝ] X)
    (h : ∀ u : ℤ → X, (∀ i, ‖u i‖ ≤ 1) → ‖u 0‖ = 1 →
      (∀ i, u (i+1) = T (u i)) → False) :
    NoSmallBoundedPseudoOrbit T := by
  classical
  by_contra hn
  -- Use the radii `1/(m+1)`; a failure of the assertion gives a pseudo orbit
  -- for every one of them.
  have hex : ∀ m : ℕ, ∃ u : ℤ → X,
        (∀ i, ‖u i‖ ≤ 1) ∧ ‖u 0‖ = 1 ∧
          (∀ i, ‖u (i+1) - T (u i)‖ ≤ (1 : ℝ) / (m+1)) := by
    intro m
    have hp : (0:ℝ) < (1:ℝ) / (m+1) := by
      exact one_div_pos.mpr (by exact_mod_cast (Nat.succ_pos m))
    have hh := hn
    -- negating the existential in the definition
    simp [NoSmallBoundedPseudoOrbit] at hh
    -- `hh` says none of the positive numbers works.
    have hh' := hh ((1:ℝ)/(m+1)) hp
    exact hh'
  choose u hu using hex
  -- all the orbits lie in the product of the closed unit balls
  let K : Set (ℤ → X) := {x | ∀ i, x i ∈ Metric.closedBall (0:X) 1}
  have hK : IsCompact K := by
    -- Tychonoff, and finite dimensional closed balls are compact
    have hc : ∀ i : ℤ, IsCompact (Metric.closedBall (0:X) 1) :=
      fun _ => isCompact_closedBall (0:X) 1
    simpa [K] using
      (isCompact_pi_infinite (X := fun _ : ℤ => X)
        (s := fun _ : ℤ => Metric.closedBall (0:X) 1) hc)
  have huK : ∀ m, u m ∈ K := by
    intro m i
    have hi := (hu m).1 i
    simpa [Metric.mem_closedBall, dist_zero_right] using hi
  obtain ⟨w, hwK, φ, hφ, hlim⟩ := hK.tendsto_subseq huK
  have hcoord (i : ℤ) :
      Tendsto (fun m : ℕ => u (φ m) i) atTop (𝓝 (w i)) := by
    have hh := (tendsto_pi_nhds.1 hlim i)
    exact hh
  have hwbound : ∀ i, ‖w i‖ ≤ 1 := by
    intro i
    have hi := hwK i
    simpa [Metric.mem_closedBall, dist_zero_right] using hi
  have hnorm0 : ‖w 0‖ = (1:ℝ) := by
    have ht : Tendsto (fun m : ℕ => ‖u (φ m) (0:ℤ)‖) atTop (𝓝 ‖w 0‖) :=
      (continuous_norm.tendsto _).comp (hcoord 0)
    have hconst : (fun m : ℕ => ‖u (φ m) (0:ℤ)‖) = fun _ => (1:ℝ) := by
      funext m
      exact (hu (φ m)).2.1
    rw [hconst] at ht
    exact tendsto_nhds_unique ht tendsto_const_nhds
  -- (The slightly pedantic proof of `hnorm0` above will be overwritten below.)
  have hstep : ∀ i : ℤ, w (i+1) = T (w i) := by
    intro i
    have hsub : Tendsto (fun m : ℕ => u (φ m) (i+1) - T (u (φ m) i)) atTop
        (𝓝 (w (i+1) - T (w i))) :=
      (hcoord (i+1)).sub (T.continuous.continuousAt.tendsto.comp (hcoord i))
    have hnorm : Tendsto
        (fun m : ℕ => ‖u (φ m) (i+1) - T (u (φ m) i)‖) atTop
        (𝓝 ‖w (i+1) - T (w i)‖) :=
      (continuous_norm.tendsto _).comp hsub
    have hzero : Tendsto (fun m : ℕ => (1:ℝ) / ((φ m)+1)) atTop (𝓝 0) := by
      exact tendsto_one_div_add_atTop_nhds_zero_nat.comp hφ.tendsto_atTop
    have hle : ∀ m : ℕ,
        ‖u (φ m) (i+1) - T (u (φ m) i)‖ ≤
          (1:ℝ) / ((φ m)+1) := by
      intro m
      exact (hu (φ m)).2.2 i
    have hnon : ∀ m : ℕ, 0 ≤
        ‖u (φ m) (i+1) - T (u (φ m) i)‖ := fun m => norm_nonneg _
    have hlimnorm : Tendsto
        (fun m : ℕ => ‖u (φ m) (i+1) - T (u (φ m) i)‖) atTop (𝓝 (0:ℝ)) :=
      squeeze_zero' (Filter.Eventually.of_forall hnon) (Filter.Eventually.of_forall hle) hzero
    have heq0 : ‖w (i+1) - T (w i)‖ = (0:ℝ) :=
      tendsto_nhds_unique hnorm hlimnorm
    exact sub_eq_zero.mp (norm_eq_zero.mp heq0)
  exact h w hwbound hnorm0 hstep

end StableSupport

-- END INLINED FILE: Mathlib/Support/stable_unstable_manifolds_da940581de/Pseudo.lean

-- BEGIN INLINED FILE: Mathlib/Support/stable_unstable_manifolds_da940581de/CompactReduction.lean

open Filter Asymptotics
open scoped Topology
namespace StableSupport

variable {X : Type*} [NormedAddCommGroup X] [NormedSpace ℝ X]

/-- Conversion of the gap lemma to an isolating neighbourhood.  Only
finite-dimensional differentiability at the fixed point is used. -/
theorem isolate_of_noSmall {f : X → X} {x₀ : X} {T : X →L[ℝ] X}
    (hd : HasFDerivAt f T x₀)
    (hfix : f x₀ = x₀)
    (hgap : NoSmallBoundedPseudoOrbit T) :
    ∃ r : ℝ, 0 < r ∧
      ∀ z : ℤ → X, (∀ i, z i ∈ Metric.ball x₀ r) →
        (∀ i, z (i+1) = f (z i)) →
        Tendsto (fun k : ℕ => z (Int.ofNat k)) atTop (𝓝 x₀) →
        Tendsto (fun k : ℕ => z (Int.negSucc k)) atTop (𝓝 x₀) →
        z 0 = x₀ := by
  classical
  rcases hgap with ⟨ε, hε, hgap⟩
  have hevent : ∀ᶠ x in 𝓝 x₀,
      ‖f x - f x₀ - T (x-x₀)‖ ≤ ε * ‖x-x₀‖ :=
    hd.isLittleO.bound hε
  rcases (Metric.mem_nhds_iff.1 hevent) with ⟨r, hr, hball⟩
  refine ⟨r, hr, ?_⟩
  intro z hzall hzstep hzpos hzneg
  by_contra hne
  have hzero : 0 < ‖z 0 - x₀‖ := (norm_pos_iff.mpr (sub_ne_zero.mpr hne))
  -- both tails of the orbit have norm strictly smaller than this positive number
  rcases (Metric.tendsto_atTop.1 hzpos _ hzero) with ⟨Np, hNp⟩
  rcases (Metric.tendsto_atTop.1 hzneg _ hzero) with ⟨Nm, hNm⟩
  let I : Finset ℤ := Finset.Icc (- (Nm:ℤ)) (Np:ℤ)
  have h0I : (0:ℤ) ∈ I := by
    simp [I]
  obtain ⟨j, hjI, hjmax⟩ := Finset.exists_max_image I
      (fun i : ℤ => ‖z i - x₀‖) ⟨0, h0I⟩
  let R : ℝ := ‖z j - x₀‖
  have hj0 : ‖z 0 - x₀‖ ≤ R := hjmax 0 h0I
  have hR : 0 < R := lt_of_lt_of_le hzero hj0
  have hmax : ∀ i : ℤ, ‖z i - x₀‖ ≤ R := by
    intro i
    by_cases hi : i ∈ I
    · exact hjmax i hi
    · have hor : i < -(Nm:ℤ) ∨ (Np:ℤ) < i := by
        have hi' : ¬ (-(Nm:ℤ) ≤ i ∧ i ≤ (Np:ℤ)) := by
          simpa [I] using hi
        omega
      rcases i with k | k
      · have hik : Np ≤ k := by
          rcases hor with hh | hh
          · change (k:ℤ) < -(Nm:ℤ) at hh
            exfalso; omega
          · change (Np:ℤ) < (k:ℤ) at hh
            omega
        have small := hNp k hik
        have hnorm : ‖z (Int.ofNat k) - x₀‖ < ‖z 0 - x₀‖ := by
          simpa [dist_eq_norm] using small
        exact (le_of_lt (lt_of_lt_of_le hnorm hj0))
      · have hik : Nm ≤ k := by
          rcases hor with hh | hh
          · simp [Int.negSucc_eq] at hh
            omega
          · exfalso
            simp [Int.negSucc_eq] at hh
            omega
        have small := hNm k hik
        have hnorm : ‖z (Int.negSucc k) - x₀‖ < ‖z 0 - x₀‖ := by
          simpa [dist_eq_norm] using small
        exact (le_of_lt (lt_of_lt_of_le hnorm hj0))
  -- the normalized shifted orbit
  let u : ℤ → X := fun i => (R⁻¹ : ℝ) • (z (j+i) - x₀)
  have hu_bound : ∀ i, ‖u i‖ ≤ (1:ℝ) := by
    intro i
    dsimp [u]
    rw [norm_smul, Real.norm_eq_abs, abs_of_nonneg (by positivity : 0 ≤ R⁻¹)]
    have hi := hmax (j+i)
    -- elementary cancellation of the positive number R
    calc
      R⁻¹ * ‖z (j+i) - x₀‖ ≤ R⁻¹ * R :=
        (mul_le_mul_of_nonneg_left hi (by positivity))
      _ = 1 := by field_simp
  have hu_one : ‖u 0‖ = (1:ℝ) := by
    dsimp [u, R]
    rw [add_zero, norm_smul, Real.norm_eq_abs,
        abs_of_nonneg (by positivity : 0 ≤ (‖z j - x₀‖)⁻¹)]
    have hn : ‖z j - x₀‖ ≠ 0 := by
      have := ne_of_gt hR
      simpa [R] using this
    exact inv_mul_cancel₀ hn
  have hu_err : ∀ i, ‖u (i+1) - T (u i)‖ ≤ ε := by
    intro i
    have hev := hball (hzall (j+i))
    -- the differentiability estimate at the source point
    have hev' : ‖f (z (j+i)) - f x₀ - T (z (j+i)-x₀)‖
          ≤ ε * ‖z (j+i)-x₀‖ := hev
    have hznext : z (j+(i+1)) = f (z (j+i)) := by
      have h := hzstep (j+i)
      simpa [add_assoc, add_left_comm, add_comm] using h
    -- unfold the normalized sequence and use linearity
    dsimp [u]
    rw [T.map_smul]
    rw [← smul_sub]
    rw [norm_smul, Real.norm_eq_abs,
       abs_of_nonneg (by positivity : 0 ≤ R⁻¹)]
    -- reduce the expression to the remainder estimate
    have heq : z (j + (i + 1)) - x₀ - T (z (j+i)-x₀) =
        f (z (j+i)) - f x₀ - T (z (j+i)-x₀) := by
      rw [hznext, hfix]
    rw [heq]
    calc
      R⁻¹ * ‖f (z (j+i)) - f x₀ - T (z (j+i) - x₀)‖
          ≤ R⁻¹ * (ε * ‖z (j+i)-x₀‖) :=
            mul_le_mul_of_nonneg_left hev' (by positivity)
      _ ≤ R⁻¹ * (ε * R) := by
            have hh := hmax (j+i)
            exact mul_le_mul_of_nonneg_left
              (mul_le_mul_of_nonneg_left hh (le_of_lt hε)) (by positivity)
      _ = ε := by field_simp
  exact hgap u hu_bound hu_one hu_err

end StableSupport

-- END INLINED FILE: Mathlib/Support/stable_unstable_manifolds_da940581de/CompactReduction.lean

-- BEGIN INLINED FILE: Mathlib/Support/stable_unstable_manifolds_da940581de/PowerSpan.lean

open Filter
namespace StableSupport

-- Vectors whose forward iterates by a linear map have a (point-dependent) bound.
-- No topology on the linear map is involved in this lemma.
variable {V : Type*} [NormedAddCommGroup V] [NormedSpace ℝ V]

def boundedPowers (D : V →ₗ[ℝ] V) : Submodule ℝ V where
  carrier := {x | ∃ c : ℝ, ∀ k : ℕ, ‖(D^k) x‖ ≤ c}
  zero_mem' := ⟨0, by intro k; simp⟩
  add_mem' := by
    intro x y hx hy
    rcases hx with ⟨a, ha⟩
    rcases hy with ⟨b, hb⟩
    refine ⟨a+b, ?_⟩
    intro k
    rw [LinearMap.map_add]
    exact le_trans (norm_add_le _ _) (add_le_add (ha k) (hb k))
  smul_mem' := by
    intro r x hx
    rcases hx with ⟨a, ha⟩
    refine ⟨‖r‖*a, ?_⟩
    intro k
    rw [LinearMap.map_smul, norm_smul]
    exact mul_le_mul_of_nonneg_left (ha k) (norm_nonneg _)

lemma mem_boundedPowers {D : V →ₗ[ℝ] V} {x : V} :
    x ∈ boundedPowers D ↔ ∃ c : ℝ, ∀ k : ℕ, ‖(D^k) x‖ ≤ c := Iff.rfl

variable {A : V →ₗ[ℝ] V} {q : ℤ → V}

lemma orbitRestriction_apply_point (h : ∀ i : ℤ, q (i+1) = A (q i)) (i : ℤ) :
    orbitRestriction A q h (⟨q i, orbit_mem_orbitSpan q i⟩ : orbitSpan q) =
      (⟨q (i+1), orbit_mem_orbitSpan q (i+1)⟩ : orbitSpan q) := by
  apply Subtype.ext
  exact (h i).symm

lemma pow_orbitRestriction_point (h : ∀ i : ℤ, q (i+1) = A (q i)) :
    ∀ (i : ℤ) (k : ℕ),
    (orbitRestriction A q h ^ k)
        (⟨q i, orbit_mem_orbitSpan q i⟩ : orbitSpan q) =
      (⟨q (i + k), orbit_mem_orbitSpan q (i+k)⟩ : orbitSpan q) := by
  intro i k
  induction k with
  | zero => simp
  | succ k ih =>
    -- `(D^(k+1)) x = D (D^k x)`
    rw [pow_succ', Module.End.mul_apply, ih,
      orbitRestriction_apply_point h]
    congr 2
    push_cast
    omega

/-- On the cyclic subspace, every vector has bounded forward iterates whenever the
orbit itself is bounded.  Bounds are allowed to depend on the vector. -/
lemma orbitRestriction_all_bounded
    (h : ∀ i : ℤ, q (i+1) = A (q i)) (hb : ∀ i : ℤ, ‖q i‖ ≤ (1:ℝ)) :
    boundedPowers (orbitRestriction A q h) = ⊤ := by
  apply top_unique
  -- it suffices that all orbit points belong to this submodule
  intro x hx
  -- show by span induction on the ambient representative
  change (x : orbitSpan q) ∈ boundedPowers (orbitRestriction A q h)
  refine Submodule.span_induction (s:= Set.range q)
    (p := fun y hy =>
      (⟨y, hy⟩ : orbitSpan q) ∈
        boundedPowers (orbitRestriction A q h)) ?_ ?_ ?_ ?_ x.property
  · intro y hy
    rcases hy with ⟨i, rfl⟩
    refine ⟨1, ?_⟩
    intro k
    rw [pow_orbitRestriction_point h]
    simpa using (hb (i+k))
  · change (0 : orbitSpan q) ∈ boundedPowers (orbitRestriction A q h)
    exact (boundedPowers (orbitRestriction A q h)).zero_mem
  · intro y z hy hz iy iz
    have hadd := (boundedPowers (orbitRestriction A q h)).add_mem iy iz
    exact hadd
  · intro a y hy iy
    exact (boundedPowers (orbitRestriction A q h)).smul_mem a iy

/-- A convenient inverse restriction. -/
noncomputable def inverseRestriction [FiniteDimensional ℝ V]
    (h : ∀ i : ℤ, q (i+1) = A (q i)) :
    orbitSpan q →ₗ[ℝ] orbitSpan q :=
  (LinearEquiv.ofBijective (orbitRestriction A q h)
    ⟨(LinearMap.injective_iff_surjective).2
       (orbitRestriction_surjective A q h),
     orbitRestriction_surjective A q h⟩).symm.toLinearMap

lemma inverseRestriction_apply_point [FiniteDimensional ℝ V]
    (h : ∀ i : ℤ, q (i+1) = A (q i)) (i : ℤ) :
    inverseRestriction h (⟨q i, orbit_mem_orbitSpan q i⟩ : orbitSpan q) =
      (⟨q (i-1), orbit_mem_orbitSpan q (i-1)⟩ : orbitSpan q) := by
  classical
  -- apply the forward equivalence
  let e : orbitSpan q ≃ₗ[ℝ] orbitSpan q :=
    LinearEquiv.ofBijective (orbitRestriction A q h)
      ⟨(LinearMap.injective_iff_surjective).2
         (orbitRestriction_surjective A q h),
       orbitRestriction_surjective A q h⟩
  change e.symm (⟨q i, orbit_mem_orbitSpan q i⟩ : orbitSpan q) = _
  apply e.injective
  simp [e]
  -- forward image of the predecessor
  have hp := orbitRestriction_apply_point h (i-1)
  simpa using hp.symm

lemma pow_inverseRestriction_point [FiniteDimensional ℝ V]
    (h : ∀ i : ℤ, q (i+1) = A (q i)) :
    ∀ (i : ℤ) (k : ℕ),
    (inverseRestriction h ^ k)
        (⟨q i, orbit_mem_orbitSpan q i⟩ : orbitSpan q) =
      (⟨q (i - k), orbit_mem_orbitSpan q (i-k)⟩ : orbitSpan q) := by
  intro i k
  induction k with
  | zero => simp
  | succ k ih =>
    rw [pow_succ', Module.End.mul_apply, ih,
      inverseRestriction_apply_point h]
    congr 2
    push_cast
    omega

lemma inverseRestriction_all_bounded [FiniteDimensional ℝ V]
    (h : ∀ i : ℤ, q (i+1) = A (q i)) (hb : ∀ i : ℤ, ‖q i‖ ≤ (1:ℝ)) :
    boundedPowers (inverseRestriction h) = (⊤ : Submodule ℝ (orbitSpan q)) := by
  apply top_unique
  intro x hx
  refine Submodule.span_induction (s:= Set.range q)
    (p := fun y hy =>
      (⟨y, hy⟩ : orbitSpan q) ∈ boundedPowers (inverseRestriction h))
      ?_ ?_ ?_ ?_ x.property
  · intro y hy
    rcases hy with ⟨i, rfl⟩
    refine ⟨1, ?_⟩
    intro k
    rw [pow_inverseRestriction_point h]
    simpa using (hb (i-k))
  · change (0 : orbitSpan q) ∈ boundedPowers (inverseRestriction h)
    exact (boundedPowers (inverseRestriction h)).zero_mem
  · intro y z hy hz iy iz
    exact (boundedPowers (inverseRestriction h)).add_mem iy iz
  · intro a y hy iy
    exact (boundedPowers (inverseRestriction h)).smul_mem a iy


end StableSupport

-- END INLINED FILE: Mathlib/Support/stable_unstable_manifolds_da940581de/PowerSpan.lean

-- BEGIN INLINED FILE: Mathlib/Support/stable_unstable_manifolds_da940581de/BoundedEigen.lean
open scoped TensorProduct ComplexConjugate
open Polynomial

namespace StableSupport
variable {V : Type*} [NormedAddCommGroup V] [NormedSpace ℝ V]

lemma tensor_complex_exists_pair (z : TensorProduct ℝ ℂ V) :
    ∃ x y : V, z = (1:ℂ) ⊗ₜ[ℝ] x + Complex.I ⊗ₜ[ℝ] y := by
  induction z using TensorProduct.induction_on with
  | zero =>
      refine ⟨0, 0, ?_⟩
      simp
  | tmul a x =>
      refine ⟨a.re • x, a.im • x, ?_⟩
      -- split a into real and imaginary parts
      rw [TensorProduct.tmul_smul, TensorProduct.tmul_smul]
      -- rhs involves real smuls on complex numbers
      -- simplify scalar action
      -- goals inspect
      have ha : a = (a.re : ℂ) + (a.im : ℂ) * Complex.I :=
        (Complex.re_add_im a).symm
      -- tensor is additive in the first argument
      calc
        a ⊗ₜ[ℝ] x = ((a.re • (1:ℂ)) + (a.im • Complex.I)) ⊗ₜ[ℝ] x := by
          congr 1
          simpa [Complex.real_smul, mul_comm] using ha
        _ = _ := TensorProduct.add_tmul _ _ _
  | add u v hu hv =>
      rcases hu with ⟨x,y,hxy⟩
      rcases hv with ⟨x',y',hxy'⟩
      refine ⟨x+x', y+y', ?_⟩
      rw [hxy, hxy']
      simp [TensorProduct.tmul_add, add_assoc, add_left_comm, add_comm]
end StableSupport

namespace StableSupport
open scoped TensorProduct
variable {V : Type*} [NormedAddCommGroup V] [NormedSpace ℝ V]

noncomputable def complexCoord (l : V →ₗ[ℝ] ℝ) :
    TensorProduct ℝ ℂ V →ₗ[ℂ] ℂ :=
  (TensorProduct.AlgebraTensorModule.rid ℝ ℂ ℂ).toLinearMap ∘ₗ
    (LinearMap.baseChange ℂ l)

@[simp] lemma complexCoord_tmul (l : V →ₗ[ℝ] ℝ) (a : ℂ) (x : V) :
    complexCoord l (a ⊗ₜ[ℝ] x) = (l x) • a := by
  simp [complexCoord, LinearMap.comp_apply, TensorProduct.AlgebraTensorModule.rid_tmul]

@[simp] lemma complexCoord_tmul_one (l : V →ₗ[ℝ] ℝ) (x y : V) :
    complexCoord l ((1:ℂ) ⊗ₜ[ℝ] x + Complex.I ⊗ₜ[ℝ] y) =
      (l x : ℂ) + (l y : ℂ) * Complex.I := by
  simp [complexCoord_tmul, Complex.real_smul]
end StableSupport
namespace StableSupport
variable {V : Type*} [NormedAddCommGroup V] [NormedSpace ℝ V]

lemma exists_real_linear_eval_ne_zero [FiniteDimensional ℝ V]
    {x : V} (hx : x ≠ 0) : ∃ l : V →ₗ[ℝ] ℝ, l x ≠ 0 := by
  classical
  let b := Module.finBasis ℝ V
  have hr : b.repr x ≠ 0 := by
    exact (b.repr.map_ne_zero_iff).2 hx
  obtain ⟨i, hi⟩ := (Finsupp.ne_iff.mp hr)
  have hi' : (b.repr x) i ≠ 0 := by
    simpa using hi
  refine ⟨b.coord i, ?_⟩
  simpa [Module.Basis.coord_apply] using hi'

lemma exists_coord_tensor_ne_zero [FiniteDimensional ℝ V]
    {w : TensorProduct ℝ ℂ V} (hw : w ≠ 0) :
    ∃ (x y : V) (l : V →ₗ[ℝ] ℝ),
       w = (1:ℂ) ⊗ₜ[ℝ] x + Complex.I ⊗ₜ[ℝ] y ∧ complexCoord l w ≠ 0 := by
  classical
  obtain ⟨x,y,hxy⟩ := tensor_complex_exists_pair w
  have hcase : x ≠ 0 ∨ y ≠ 0 := by
    by_contra h
    push_neg at h
    exact hw (by simp [hxy, h.1, h.2])
  rcases hcase with hx | hy
  · obtain ⟨l, hl⟩ := exists_real_linear_eval_ne_zero hx
    refine ⟨x,y,l,hxy, ?_⟩
    rw [hxy, complexCoord_tmul_one]
    intro hz
    -- compare real part
    have hr := congrArg Complex.re hz
    -- real part is l x
    have : l x = 0 := by
      simpa using hr
    exact hl this
  · obtain ⟨l, hl⟩ := exists_real_linear_eval_ne_zero hy
    refine ⟨x,y,l,hxy, ?_⟩
    rw [hxy, complexCoord_tmul_one]
    intro hz
    have hi := congrArg Complex.im hz
    have : l y = 0 := by
      simpa using hi
    exact hl this
end StableSupport
namespace StableSupport
open scoped TensorProduct
variable {V : Type*} [NormedAddCommGroup V] [NormedSpace ℝ V]

lemma baseChange_pow (D : V →ₗ[ℝ] V) (k : ℕ) :
    (LinearMap.baseChange ℂ D : Module.End ℂ (TensorProduct ℝ ℂ V)) ^ k =
      LinearMap.baseChange ℂ (D^k) := by
  induction k with
  | zero =>
      simpa using (LinearMap.baseChange_id (R:=ℝ) (A:=ℂ) (M:=V))
  | succ k ih =>
      rw [pow_succ', ih, pow_succ']
      -- multiplication is composition
      change (LinearMap.baseChange ℂ D) ∘ₗ (LinearMap.baseChange ℂ (D^k)) =
        LinearMap.baseChange ℂ (D ∘ₗ (D^k))
      exact (LinearMap.baseChange_comp (A:=ℂ) (D^k) D).symm

lemma baseChange_pow_tmul (D : V →ₗ[ℝ] V) (k : ℕ) (a : ℂ) (x : V) :
    ((LinearMap.baseChange ℂ D)^k) (a ⊗ₜ[ℝ] x) =
      a ⊗ₜ[ℝ] ((D^k) x) := by
  rw [baseChange_pow]
  exact LinearMap.baseChange_tmul _ _ _
end StableSupport
namespace StableSupport
lemma pow_eigenvector {U : Type*} [AddCommGroup U] [Module ℂ U]
    (T : Module.End ℂ U) (μ : ℂ) (w : U)
    (h : T w = μ • w) :
    ∀ k : ℕ, (T^k) w = (μ^k) • w := by
  intro k
  induction k with
  | zero => simp
  | succ k ih =>
    rw [pow_succ', Module.End.mul_apply, ih]
    -- linear
    simp [LinearMap.map_smulₛₗ, h, smul_smul, pow_succ]
end StableSupport
namespace StableSupport
open scoped TensorProduct
open Polynomial
variable {V : Type*} [NormedAddCommGroup V] [NormedSpace ℝ V]
  [FiniteDimensional ℝ V]

/-- Pointwise bounded real powers force any complex eigenvalue (after scalar extension)
 to have modulus at most one. -/
lemma norm_eigen_le_one (D : V →ₗ[ℝ] V)
    (hb : boundedPowers D = ⊤) (μ : ℂ)
    (he : Module.End.HasEigenvalue (LinearMap.baseChange ℂ D : Module.End ℂ (TensorProduct ℝ ℂ V)) μ) :
    ‖μ‖ ≤ (1:ℝ) := by
  classical
  obtain ⟨w, hw⟩ := he.exists_hasEigenvector
  have hw0 : w ≠ 0 := hw.2
  have hwe : (LinearMap.baseChange ℂ D : Module.End ℂ (TensorProduct ℝ ℂ V)) w = μ • w :=
    hw.apply_eq_smul
  obtain ⟨x, y, l, hxy, hc⟩ := exists_coord_tensor_ne_zero (V:=V) hw0
  -- individual real iterates have bounds
  have hbx : x ∈ boundedPowers D := by
    rw [hb]; trivial
  have hby : y ∈ boundedPowers D := by
    rw [hb]; trivial
  rcases hbx with ⟨Mx, hMx⟩
  rcases hby with ⟨My, hMy⟩
  have Mx0 : 0 ≤ Mx := le_trans (norm_nonneg x) (by simpa using hMx 0)
  have My0 : 0 ≤ My := le_trans (norm_nonneg y) (by simpa using hMy 0)
  let lc : V →L[ℝ] ℝ := LinearMap.toContinuousLinearMap l
  let R : ℝ := ‖lc‖
  have R0 : 0 ≤ R := norm_nonneg _
  let c : ℂ := complexCoord l w
  have c0 : c ≠ 0 := hc
  have cn0 : 0 < ‖c‖ := norm_pos_iff.mpr c0
  have hcform : c = (l x : ℂ) + (l y : ℂ) * Complex.I := by
    dsimp [c]
    simpa [hxy] using (complexCoord_tmul_one l x y)
  have hrealx : ∀ k : ℕ, ‖l ((D^k) x)‖ ≤ R * Mx := by
    intro k
    calc
      ‖l ((D^k) x)‖ = ‖lc ((D^k) x)‖ := rfl
      _ ≤ R * ‖(D^k) x‖ := by
        dsimp [R]
        exact ContinuousLinearMap.le_opNorm lc _
      _ ≤ R * Mx := mul_le_mul_of_nonneg_left (hMx k) R0
  have hrealy : ∀ k : ℕ, ‖l ((D^k) y)‖ ≤ R * My := by
    intro k
    calc
      ‖l ((D^k) y)‖ = ‖lc ((D^k) y)‖ := rfl
      _ ≤ R * ‖(D^k) y‖ := by
        dsimp [R]
        exact ContinuousLinearMap.le_opNorm lc _
      _ ≤ R * My := mul_le_mul_of_nonneg_left (hMy k) R0
  -- uniform upper bound on the observed complex orbit
  have horb : ∀ k : ℕ,
      ‖complexCoord l
          (((LinearMap.baseChange ℂ D : Module.End ℂ (TensorProduct ℝ ℂ V))^k) w)‖
          ≤ R * Mx + R * My := by
    intro k
    have hpowform :
        (((LinearMap.baseChange ℂ D : Module.End ℂ (TensorProduct ℝ ℂ V))^k) w) =
          (1:ℂ) ⊗ₜ[ℝ] ((D^k) x) + Complex.I ⊗ₜ[ℝ] ((D^k) y) := by
      rw [hxy]
      rw [LinearMap.map_add]
      rw [baseChange_pow_tmul, baseChange_pow_tmul]
    rw [hpowform, complexCoord_tmul_one]
    calc
      ‖(l ((D ^ k) x) : ℂ) +
          (l ((D ^ k) y) : ℂ) * Complex.I‖
          ≤ ‖(l ((D ^ k) x) : ℂ)‖ +
              ‖(l ((D ^ k) y) : ℂ) * Complex.I‖ := norm_add_le _ _
      _ = ‖l ((D^k) x)‖ + ‖l ((D^k) y)‖ := by
        rw [norm_mul, Complex.norm_I]
        -- ofReal norm is real norm
        simp [Complex.norm_real]
      _ ≤ R * Mx + R * My := add_le_add (hrealx k) (hrealy k)
  -- eigen equation computes the same orbit exactly
  have hevpow : ∀ k : ℕ,
        ((LinearMap.baseChange ℂ D : Module.End ℂ (TensorProduct ℝ ℂ V))^k) w =
          (μ^k) • w := pow_eigenvector _ _ _ hwe
  have hbound : ∀ k : ℕ, (‖μ‖^k) * ‖c‖ ≤ R * Mx + R * My := by
    intro k
    have h := horb k
    rw [hevpow k] at h
    -- apply linearity of the observation
    change ‖complexCoord l ((μ^k) • w)‖ ≤ _ at h
    rw [LinearMap.map_smul] at h
    -- transform norm_smul
    simpa [norm_smul, Complex.norm_pow, c] using h
  by_contra hnot
  have hgt : (1:ℝ) < ‖μ‖ := lt_of_not_ge hnot
  obtain ⟨k, hk⟩ := pow_unbounded_of_one_lt ((R * Mx + R * My) / ‖c‖) hgt
  have hm := hbound k
  have hmul : (R * Mx + R * My) < (‖μ‖^k) * ‖c‖ := by
    -- multiply hk by the positive norm
    have h := (mul_lt_mul_of_pos_right hk cn0)
    -- simplify division
    -- hk : (C / norm) < pow
    -- h : C/norm * norm < pow * norm
    have hn : ‖c‖ ≠ 0 := ne_of_gt cn0
    simpa [div_mul_eq_mul_div, hn] using h
  exact (not_lt_of_ge hm) hmul
end StableSupport
namespace StableSupport
open scoped TensorProduct
open Polynomial
variable {V : Type*} [NormedAddCommGroup V] [NormedSpace ℝ V]
  [FiniteDimensional ℝ V]

/-- Combining the previous estimate for an endomorphism and a left inverse. -/
lemma norm_eigen_eq_one_of_inverse (D E : V →ₗ[ℝ] V)
    (hED : E ∘ₗ D = LinearMap.id)
    (hbD : boundedPowers D = ⊤) (hbE : boundedPowers E = ⊤)
    {μ : ℂ}
    (he : Module.End.HasEigenvalue
      (LinearMap.baseChange ℂ D : Module.End ℂ (TensorProduct ℝ ℂ V)) μ) :
    ‖μ‖ = (1:ℝ) := by
  classical
  let D' : Module.End ℂ (TensorProduct ℝ ℂ V) := LinearMap.baseChange ℂ D
  let E' : Module.End ℂ (TensorProduct ℝ ℂ V) := LinearMap.baseChange ℂ E
  have hcomp : E' ∘ₗ D' = LinearMap.id := by
    dsimp [E', D']
    rw [← LinearMap.baseChange_comp, hED]
    exact LinearMap.baseChange_id
  obtain ⟨w, hw⟩ := he.exists_hasEigenvector
  have hw0 : w ≠ 0 := hw.2
  have hwD : D' w = μ • w := by
    exact hw.apply_eq_smul
  have hEDw : E' (D' w) = w := by
    have h := LinearMap.congr_fun hcomp w
    simpa [LinearMap.comp_apply] using h
  have hμ0 : μ ≠ 0 := by
    intro hm
    have hz : D' w = 0 := by simpa [hm] using hwD
    have : w = 0 := by
      calc w = E' (D' w) := hEDw.symm
           _ = 0 := by rw [hz]; exact LinearMap.map_zero _
    exact hw0 this
  have hwE : E' w = μ⁻¹ • w := by
    apply (eq_inv_smul_iff₀ hμ0).2
    -- want μ • E' w = w
    have h := hEDw
    rw [hwD] at h
    simpa using h
  have heE : Module.End.HasEigenvalue E' (μ⁻¹) := by
    apply Module.End.hasEigenvalue_of_hasEigenvector
    refine ⟨(Module.End.mem_eigenspace_iff).2 hwE, hw0⟩
  have hle : ‖μ‖ ≤ (1:ℝ) := norm_eigen_le_one D hbD μ he
  have hle' : ‖(μ⁻¹)‖ ≤ (1:ℝ) := by
    exact norm_eigen_le_one E hbE (μ⁻¹) heE
  have hpos : (0:ℝ) < ‖μ‖ := norm_pos_iff.mpr hμ0
  have hge : (1:ℝ) ≤ ‖μ‖ := by
    have hi : (‖μ‖)⁻¹ ≤ (1:ℝ) := by simpa [norm_inv] using hle'
    exact (inv_le_one₀ hpos).1 hi
  exact le_antisymm hle hge
end StableSupport

-- END INLINED FILE: Mathlib/Support/stable_unstable_manifolds_da940581de/BoundedEigen.lean

namespace Submission

-- BEGIN INLINED FILE: Main.lean

namespace LeanEval
namespace Dynamics
namespace StableUnstableManifoldsProblem

/-!
# Local stable and unstable sets at a hyperbolic fixed point

For a `C¹` map `f : ℝⁿ → ℝⁿ` with a hyperbolic invertible fixed point at
`x₀`, some open neighbourhood `U ∋ x₀` carries genuinely local stable
and unstable sets — orbits required to stay inside `U` while converging
to `x₀` — meeting only at `x₀`. This is the set-level (topological)
shadow of the Hadamard–Perron theorem; the full theorem additionally
asserts that the local stable and unstable sets are immersed `C¹`
submanifolds tangent to the stable / unstable eigenspaces. §104 in
Knill's *Some Fundamental Theorems in Mathematics*.

The "orbit stays in `U`" requirement is essential: without it, homoclinic
points (forward and backward limits at `x₀`, but excursions outside any
small neighbourhood) would falsify `Wˢ ∩ Wᵘ = {x₀}` in systems with
homoclinic dynamics. With it, after shrinking `U`, the only point with
both forward and backward orbits remaining in `U` and converging to
`x₀` is `x₀` itself.
-/

open scoped Topology
open Filter Polynomial

/-- The Euclidean model space `ℝⁿ`. -/
abbrev E (n : ℕ) : Type := EuclideanSpace ℝ (Fin n)

/-- Multiset of complex eigenvalues of `L : ℝⁿ →L[ℝ] ℝⁿ`. -/
noncomputable def complexEigenvalues {n : ℕ} (L : E n →L[ℝ] E n) : Multiset ℂ :=
  ((L : E n →ₗ[ℝ] E n).charpoly.map (algebraMap ℝ ℂ)).roots

/-- `L` is **hyperbolic**: no complex eigenvalue lies on the unit
circle. -/
def IsHyperbolicLinear {n : ℕ} (L : E n →L[ℝ] E n) : Prop :=
  ∀ μ ∈ complexEigenvalues L, ‖μ‖ ≠ 1



end StableUnstableManifoldsProblem
end Dynamics
end LeanEval

open LeanEval.Dynamics.StableUnstableManifoldsProblem
open scoped Topology
open Filter Polynomial
/-ResultDefinitionsBegin-/
/-ResultProofDefinitionsBegin-/
/-ResultProofDefinitionsEnd-/
/-ResultDefinitionsEnd-/

/-ResultBegin-/

theorem stable_unstable_manifolds_exist (n : ℕ) (f : E n → E n) (x₀ : E n)
    (_hf : ContDiffAt ℝ 1 f x₀)
    (_hfix : f x₀ = x₀)
    (_hhyp : IsHyperbolicLinear (fderiv ℝ f x₀))
    (_hf_inv : (fderiv ℝ f x₀).IsInvertible) :
    ∃ U : Set (E n), IsOpen U ∧ x₀ ∈ U ∧
      ∃ Ws Wu : Set (E n),
        Ws = {x | (∀ k : ℕ, f^[k] x ∈ U) ∧
                  Tendsto (fun k => f^[k] x) atTop (𝓝 x₀)} ∧
        Wu = {x | ∃ y : ℕ → E n,
                    y 0 = x ∧
                    (∀ k : ℕ, y k ∈ U) ∧
                    (∀ k : ℕ, f (y (k + 1)) = y k) ∧
                    Tendsto y atTop (𝓝 x₀)} ∧
        Ws ∩ Wu = {x₀} :=
/-ResultProofBegin-/by
  classical
  have hdiff : DifferentiableAt ℝ f x₀ := _hf.differentiableAt (by norm_num)
  have hfd : HasFDerivAt f (fderiv ℝ f x₀) x₀ := hdiff.hasFDerivAt
  have hlin : StableSupport.NoSmallBoundedPseudoOrbit (fderiv ℝ f x₀) := by
    apply StableSupport.noSmall_of_no_exact (fderiv ℝ f x₀)
    intro v hv hvone hstep
    -- The remaining, entirely linear, dichotomy assertion: a hyperbolic
    -- invertible matrix has no bounded normalised full orbit.  Passing
    -- to the cyclic subspace packages the two algebraic facts usually
    -- used before splitting over `ℂ`.
    let A : E n →ₗ[ℝ] E n := (fderiv ℝ f x₀).toLinearMap
    have hs : ∀ i : ℤ, v (i+1) = A (v i) := hstep
    have hne : v 0 ≠ 0 := by
      intro hz
      have : (0:ℝ) = 1 := by simpa [hz] using hvone
      norm_num at this
    have hn : n ≠ 0 := by
      intro hdim
      subst n
      apply hne
      exact Subsingleton.elim _ _
    let W : Submodule ℝ (E n) := StableSupport.orbitSpan v
    have hW : W ≠ ⊥ := StableSupport.orbitSpan_ne_bot v 0 hne
    have hAW : Submodule.map A W = W :=
      StableSupport.map_orbitSpan A v hs
    let B : W →ₗ[ℝ] W := StableSupport.orbitRestriction A v hs
    have hB : Function.Surjective B :=
      StableSupport.orbitRestriction_surjective A v hs
    -- At this point it is the finite-dimensional spectral lemma: a
    -- nonzero invariant cyclic subspace on which both directions of an
    -- orbit are bounded has a complex eigenvalue of modulus one.  The
    -- active remaining step is this precise root-production statement;
    -- all the nonlinear and compactness parts have been peeled away.
    have hbB : StableSupport.boundedPowers B = ⊤ := by
      dsimp [B]
      exact StableSupport.orbitRestriction_all_bounded hs hv
    let C : W →ₗ[ℝ] W := StableSupport.inverseRestriction hs
    have hbC : StableSupport.boundedPowers C = ⊤ := by
      dsimp [C]
      exact StableSupport.inverseRestriction_all_bounded hs hv
    letI : Nontrivial W :=
      (Submodule.nontrivial_iff_ne_bot.mpr hW)
    obtain ⟨μ, hμ⟩ := StableSupport.exists_complex_root (W:=W)
      (inferInstance : Nontrivial W) B
    have hint : W.subtype ∘ₗ B = A ∘ₗ W.subtype := by
      ext w
      rfl
    have hma : (A.charpoly.map (algebraMap ℝ ℂ)).IsRoot μ :=
      StableSupport.ambient_root_of_restriction A W B hint hμ
    have hmem : μ ∈ complexEigenvalues (fderiv ℝ f x₀) := by
      unfold complexEigenvalues
      apply (Polynomial.mem_roots
        ((LinearMap.charpoly_monic A).map (algebraMap ℝ ℂ) |>.ne_zero)).2
      exact hma
    have hmod : ‖μ‖ = (1:ℝ) := by
      -- Remaining spectral estimate, now only on the finite dimensional
      -- cyclic subspace.  We have acquired an eigenvalue of its
      -- complexification; `hbB` and `hbC` say that every real vector has
      -- bounded powers of the restriction and its inverse.  Splitting an
      -- eigenvector into real and imaginary coordinate vectors gives
      -- `‖μ‖ ≤ 1` and `1 ≤ ‖μ‖`, respectively.
      have hinjB : Function.Injective B :=
        (LinearMap.injective_iff_surjective).2 hB
      obtain ⟨p, hp⟩ := B.exists_leftInverse_of_injective
        ((LinearMap.ker_eq_bot).2 hinjB)
      have hp' : (LinearMap.baseChange ℂ p) ∘ₗ
            (LinearMap.baseChange ℂ B) = LinearMap.id := by
        rw [← LinearMap.baseChange_comp, hp]
        exact LinearMap.baseChange_id
      have hi' : Function.Injective (LinearMap.baseChange ℂ B) := by
        intro a b hab
        have hab' := congrArg (fun t => (LinearMap.baseChange ℂ p) t) hab
        calc
          a = (LinearMap.baseChange ℂ p) ((LinearMap.baseChange ℂ B) a) := by
            rw [← LinearMap.comp_apply, hp']; rfl
          _ = (LinearMap.baseChange ℂ p) ((LinearMap.baseChange ℂ B) b) := hab'
          _ = b := by rw [← LinearMap.comp_apply, hp']; rfl
      let B' : Module.End ℂ (TensorProduct ℝ ℂ W) :=
        LinearMap.baseChange ℂ B
      have heigen : B'.HasEigenvalue μ := by
        apply (Module.End.hasEigenvalue_iff_isRoot_charpoly B' _).2
        simpa [B', LinearMap.charpoly_baseChange] using hμ
      have hμzero : μ ≠ (0:ℂ) := by
        obtain ⟨w, hw⟩ := heigen.exists_hasEigenvector
        intro hm
        have hz : (LinearMap.baseChange ℂ B) w = 0 := by
          simpa [hm] using hw.apply_eq_smul
        have : w = 0 := hi' (by simpa using hz)
        exact hw.2 this
      have hμpos : (0:ℝ) < ‖μ‖ := (norm_pos_iff.mpr hμzero)
      have hCB : C ∘ₗ B = LinearMap.id := by
        -- `C` was defined to be the inverse of `B` on its orbit span.
        dsimp [C, StableSupport.inverseRestriction]
        -- Write the bijective restriction as a linear equivalence.
        let e : W ≃ₗ[ℝ] W :=
          LinearEquiv.ofBijective
            (StableSupport.orbitRestriction A v hs)
            ⟨(LinearMap.injective_iff_surjective).2
                (StableSupport.orbitRestriction_surjective A v hs),
              StableSupport.orbitRestriction_surjective A v hs⟩
        change e.symm.toLinearMap ∘ₗ e.toLinearMap = LinearMap.id
        ext w
        simp
      have he' : Module.End.HasEigenvalue
          (LinearMap.baseChange ℂ B : Module.End ℂ (TensorProduct ℝ ℂ W)) μ := by
        simpa [B'] using heigen
      exact StableSupport.norm_eigen_eq_one_of_inverse B C hCB hbB hbC he' 
    have hroot : ∃ μ : ℂ,
        μ ∈ complexEigenvalues (fderiv ℝ f x₀) ∧ ‖μ‖ = (1:ℝ) :=
      ⟨μ, hmem, hmod⟩
    rcases hroot with ⟨μ, hμ, hμone⟩
    exact (_hhyp μ hμ) hμone
  rcases StableSupport.isolate_of_noSmall hfd _hfix hlin with ⟨r, hr, hiso⟩
  refine ⟨Metric.ball x₀ r, Metric.isOpen_ball, Metric.mem_ball_self hr, ?_⟩
  refine ⟨{x | (∀ k : ℕ, f^[k] x ∈ Metric.ball x₀ r) ∧
                  Tendsto (fun k => f^[k] x) atTop (𝓝 x₀)},
           {x | ∃ y : ℕ → E n,
                    y 0 = x ∧
                    (∀ k : ℕ, y k ∈ Metric.ball x₀ r) ∧
                    (∀ k : ℕ, f (y (k + 1)) = y k) ∧
                    Tendsto y atTop (𝓝 x₀)}, rfl, rfl, ?_⟩
  ext x
  constructor
  · intro hx
    rcases hx with ⟨⟨hxU, hxlim⟩, hy⟩
    rcases hy with ⟨y, hy0, hyU, hystep, hylim⟩
    let z : ℤ → E n
      | Int.ofNat k => f^[k] x
      | Int.negSucc k => y (k+1)
    have hzU : ∀ i : ℤ, z i ∈ Metric.ball x₀ r := by
      intro i
      cases i with
      | ofNat k => exact hxU k
      | negSucc k => exact hyU (k+1)
    have hzstep : ∀ i : ℤ, z (i+1) = f (z i) := by
      intro i
      cases i with
      | ofNat k =>
          change f^[k+1] x = f (f^[k] x)
          simpa using (Function.iterate_succ_apply' f k x)
      | negSucc k =>
          cases k with
          | zero =>
              change f^[0] x = f (y (0+1))
              simpa [hy0] using (hystep 0).symm
          | succ k =>
              change y (k+1) = f (y ((k+1)+1))
              simpa using (hystep (k+1)).symm
    have hzpos : Tendsto (fun k : ℕ => z (Int.ofNat k)) atTop (𝓝 x₀) := by
      simpa [z] using hxlim
    have hzneg : Tendsto (fun k : ℕ => z (Int.negSucc k)) atTop (𝓝 x₀) := by
      -- this is the tail of the backwards orbit
      have ht : Tendsto (fun k : ℕ => y (k+1)) atTop (𝓝 x₀) :=
        hylim.comp (tendsto_add_atTop_nat 1)
      simpa [z] using ht
    have hz0 := hiso z hzU hzstep hzpos hzneg
    have hx0 : x = x₀ := by simpa [z] using hz0
    simpa [hx0]
  · intro hx
    have hx0 : x = x₀ := by simpa using hx
    subst x
    constructor
    · refine ⟨?_, ?_⟩
      · intro k
        simpa [Function.iterate_fixed _hfix] using (Metric.mem_ball_self (x:=x₀) hr)
      · have H : (fun k : ℕ => f^[k] x₀) = fun _ => x₀ := by
          funext k
          exact Function.iterate_fixed _hfix k
        rw [H]
        exact tendsto_const_nhds
    · refine ⟨(fun _ : ℕ => x₀), rfl, ?_, ?_, ?_⟩
      · intro k
        exact Metric.mem_ball_self hr
      · intro k
        exact _hfix
      · exact tendsto_const_nhds
/-ResultProofEnd-/
/-ResultEnd-/
-- END INLINED FILE: Main.lean

end Submission
